export type ClientKycQuestion = {
  id: string;
  section: string;
  label: string;
  helpText: string;
  kind: "text" | "textarea" | "select" | "repeatable-group";
  required: boolean;
  options?: readonly string[];
  subFields?: Array<{
    id: string;
    label: string;
    helpText?: string;
    kind: "text" | "textarea" | "select";
    required: boolean;
    options?: readonly string[];
  }>;
};

// Seeded questions are the temporary questionnaire template until the admin editor is introduced.
export const CLIENT_KYC_QUESTIONS: readonly ClientKycQuestion[] = [
  {
    id: "customer_type",
    section: "Section A - Customer type",
    label: "Customer type",
    helpText: "Select the customer classification that best describes the applicant.",
    kind: "select",
    required: true,
    options: ["Individual", "Sole proprietor", "Company", "Partnership", "Trust", "Organization / Institution"],
  },
  {
    id: "full_legal_name",
    section: "Section B - Individual customer details",
    label: "Full legal name",
    helpText: "Enter the full legal name exactly as it appears on your identification document.",
    kind: "text",
    required: true,
  },
  {
    id: "date_of_birth",
    section: "Section B - Individual customer details",
    label: "Date of birth",
    helpText: "Enter the date of birth in YYYY-MM-DD format.",
    kind: "text",
    required: true,
  },
  {
    id: "nationality",
    section: "Section B - Individual customer details",
    label: "Nationality",
    helpText: "Select the nationality shown on your identification document.",
    kind: "select",
    required: true,
    options: ["Kenyan", "Other East African", "Other"],
  },
  {
    id: "gender",
    section: "Section B - Individual customer details",
    label: "Gender",
    helpText: "Share the gender that best fits your records.",
    kind: "select",
    required: false,
    options: ["Male", "Female", "Non-binary", "Prefer not to say"],
  },
  {
    id: "national_id",
    section: "Section B - Individual customer details",
    label: "National ID number",
    helpText: "Enter the national identification number shown on your ID document.",
    kind: "text",
    required: true,
  },
  {
    id: "id_document_type",
    section: "Section B - Individual customer details",
    label: "ID document type",
    helpText: "Select the document type used as your primary identification.",
    kind: "select",
    required: true,
    options: ["National ID", "Passport", "Alien ID", "Driver's licence"],
  },
  {
    id: "kra_pin",
    section: "Section B - Individual customer details",
    label: "KRA PIN",
    helpText: "Enter the KRA PIN assigned to the applicant.",
    kind: "text",
    required: true,
  },
  {
    id: "phone_number",
    section: "Section B - Individual customer details",
    label: "Phone number",
    helpText: "Provide the best contact number for the applicant.",
    kind: "text",
    required: true,
  },
  {
    id: "email_address",
    section: "Section B - Individual customer details",
    label: "Email address",
    helpText: "Provide the primary email address for correspondence.",
    kind: "text",
    required: true,
  },
  {
    id: "physical_address",
    section: "Section B - Individual customer details",
    label: "Physical address",
    helpText: "Include the street, building, town, and country.",
    kind: "textarea",
    required: true,
  },
  {
    id: "postal_address",
    section: "Section B - Individual customer details",
    label: "Postal address",
    helpText: "Provide the postal address where documents can be delivered.",
    kind: "textarea",
    required: true,
  },
  {
    id: "country",
    section: "Section B - Individual customer details",
    label: "Country",
    helpText: "Select the country of residence or incorporation.",
    kind: "select",
    required: true,
    options: ["Kenya", "Uganda", "Tanzania", "Rwanda", "Other"],
  },
  {
    id: "occupation",
    section: "Section B - Individual customer details",
    label: "Occupation",
    helpText: "Describe the applicant's current occupation or profession.",
    kind: "text",
    required: false,
  },
  {
    id: "business_name",
    section: "Section B - Individual customer details",
    label: "Business name",
    helpText: "Enter the applicant's business name, if applicable.",
    kind: "text",
    required: false,
  },
  {
    id: "source_of_income",
    section: "Section B - Individual customer details",
    label: "Source of income",
    helpText: "Select the main source of funds supporting the expected activity.",
    kind: "select",
    required: true,
    options: ["Employment income", "Business income", "Investments", "Inheritance", "Other"],
  },
  {
    id: "estimated_monthly_income",
    section: "Section B - Individual customer details",
    label: "Estimated monthly income",
    helpText: "Provide the estimated monthly income in local currency.",
    kind: "text",
    required: false,
  },
  {
    id: "customer_image",
    section: "Section B - Individual customer details",
    label: "Customer image",
    helpText: "Upload a recent passport-size photo or selfie when available.",
    kind: "text",
    required: false,
  },
  {
    id: "registered_business_name",
    section: "Section C - Business or company details",
    label: "Registered business name",
    helpText: "Enter the full registered business or company name.",
    kind: "text",
    required: false,
  },
  {
    id: "business_registration_number",
    section: "Section C - Business or company details",
    label: "Business registration or incorporation number",
    helpText: "Enter the registration or incorporation number issued by the regulator.",
    kind: "text",
    required: false,
  },
  {
    id: "business_type",
    section: "Section C - Business or company details",
    label: "Business type",
    helpText: "Select the legal form of the entity.",
    kind: "select",
    required: false,
    options: ["Limited company", "Partnership", "Sole proprietorship", "Trust", "Association", "Other"],
  },
  {
    id: "date_of_registration",
    section: "Section C - Business or company details",
    label: "Date of registration",
    helpText: "Enter the date of registration in YYYY-MM-DD format.",
    kind: "text",
    required: false,
  },
  {
    id: "registered_office_address",
    section: "Section C - Business or company details",
    label: "Registered office address",
    helpText: "Include the official registered address of the business.",
    kind: "textarea",
    required: false,
  },
  {
    id: "business_phone_number",
    section: "Section C - Business or company details",
    label: "Phone number",
    helpText: "Provide the main business contact number.",
    kind: "text",
    required: false,
  },
  {
    id: "business_email",
    section: "Section C - Business or company details",
    label: "Business email",
    helpText: "Provide the primary business email address.",
    kind: "text",
    required: false,
  },
  {
    id: "business_website",
    section: "Section C - Business or company details",
    label: "Website",
    helpText: "Provide your website address where applicable.",
    kind: "text",
    required: false,
  },
  {
    id: "nature_of_business",
    section: "Section C - Business or company details",
    label: "Nature of business",
    helpText: "Describe the core business activity and trading model.",
    kind: "textarea",
    required: false,
  },
  {
    id: "expected_transaction_volume",
    section: "Section C - Business or company details",
    label: "Expected transaction volume",
    helpText: "Estimate the expected transaction volume for the relationship.",
    kind: "text",
    required: false,
  },
  {
    id: "source_of_business_funds",
    section: "Section C - Business or company details",
    label: "Source of business funds",
    helpText: "Explain where the business funds supporting the activity come from.",
    kind: "textarea",
    required: false,
  },
  {
    id: "directors_owners_beneficiaries",
    section: "Section D - Directors, owners and beneficiaries",
    label: "Directors, owners and beneficiaries",
    helpText: "Add each director, owner, or beneficial owner and their relevant details.",
    kind: "repeatable-group",
    required: false,
    subFields: [
      { id: "full_name", label: "Full name", kind: "text", required: true },
      { id: "nationality", label: "Nationality", kind: "text", required: true },
      { id: "national_id", label: "National ID", kind: "text", required: true },
      { id: "phone_number", label: "Phone number", kind: "text", required: true },
      { id: "email", label: "Email", kind: "text", required: true },
      { id: "position", label: "Position", kind: "text", required: true },
      { id: "percentage_ownership", label: "Percentage of ownership", kind: "text", required: false },
      { id: "kra_pin", label: "KRA PIN", kind: "text", required: false },
    ],
  },
  {
    id: "purpose_of_registration",
    section: "Section E - Purpose and expected activity",
    label: "Why are you registering?",
    helpText: "Describe the reason for opening the relationship and the services being requested.",
    kind: "textarea",
    required: true,
  },
  {
    id: "products_or_services",
    section: "Section E - Purpose and expected activity",
    label: "What products or services will you use?",
    helpText: "List the products or services the customer expects to use.",
    kind: "textarea",
    required: true,
  },
  {
    id: "expected_monthly_transaction_amount",
    section: "Section E - Purpose and expected activity",
    label: "Expected monthly transaction amount",
    helpText: "Estimate the monthly transaction value expected from this relationship.",
    kind: "text",
    required: false,
  },
  {
    id: "expected_number_of_transactions",
    section: "Section E - Purpose and expected activity",
    label: "Expected number of transactions",
    helpText: "Estimate the number of transactions expected each month.",
    kind: "text",
    required: false,
  },
  {
    id: "main_payment_methods",
    section: "Section E - Purpose and expected activity",
    label: "Main payment methods",
    helpText: "List the payment methods you expect to use, such as bank transfer or card.",
    kind: "textarea",
    required: false,
  },
  {
    id: "payment_countries",
    section: "Section E - Purpose and expected activity",
    label: "Countries from or to which payments are expected",
    helpText: "List any countries involved in the expected payment flows.",
    kind: "textarea",
    required: false,
  },
  {
    id: "source_of_funds",
    section: "Section E - Purpose and expected activity",
    label: "Source of funds",
    helpText: "Describe the source of the funds that will be used for this activity.",
    kind: "textarea",
    required: true,
  },
  {
    id: "source_of_wealth",
    section: "Section E - Purpose and expected activity",
    label: "Source of wealth",
    helpText: "Provide the source of wealth, especially for higher-risk customers.",
    kind: "textarea",
    required: false,
  },
  {
    id: "acting_on_behalf",
    section: "Section F - Compliance and risk questions",
    label: "Are you acting on behalf of another person?",
    helpText: "Select whether you are acting as an intermediary or representative.",
    kind: "select",
    required: true,
    options: ["No", "Yes"],
  },
  {
    id: "politically_exposed",
    section: "Section F - Compliance and risk questions",
    label: "Are you or any beneficial owners politically exposed persons?",
    helpText: "Select the answer that applies to the applicant and beneficial owners.",
    kind: "select",
    required: true,
    options: ["No", "Yes"],
  },
  {
    id: "related_to_pep",
    section: "Section F - Compliance and risk questions",
    label: "Are you related or closely associated with a politically exposed person?",
    helpText: "Select the answer that applies to the applicant and beneficial owners.",
    kind: "select",
    required: true,
    options: ["No", "Yes"],
  },
  {
    id: "operates_outside_kenya",
    section: "Section F - Compliance and risk questions",
    label: "Do you operate outside Kenya?",
    helpText: "Select whether the applicant operates outside Kenya.",
    kind: "select",
    required: true,
    options: ["No", "Yes"],
  },
  {
    id: "international_payments",
    section: "Section F - Compliance and risk questions",
    label: "Do you receive or send international payments?",
    helpText: "Select whether the applicant receives or sends international transfers.",
    kind: "select",
    required: true,
    options: ["No", "Yes"],
  },
  {
    id: "regulated_or_high_risk_industry",
    section: "Section F - Compliance and risk questions",
    label: "Are you involved in a regulated or high-risk industry?",
    helpText: "Select whether the applicant operates in a regulated or higher-risk sector.",
    kind: "select",
    required: true,
    options: ["No", "Yes"],
  },
  {
    id: "previous_financial_crimes",
    section: "Section F - Compliance and risk questions",
    label: "Have you previously been investigated or convicted for financial crimes?",
    helpText: "Select whether the applicant has prior financial crime investigations or convictions.",
    kind: "select",
    required: true,
    options: ["No", "Yes"],
  },
  {
    id: "third_party_funds",
    section: "Section F - Compliance and risk questions",
    label: "Are any funds being provided by a third party?",
    helpText: "Select whether any funds are being provided by a third party.",
    kind: "select",
    required: true,
    options: ["No", "Yes"],
  },
  {
    id: "compliance_risk_questions",
    section: "Section F - Compliance and risk questions",
    label: "Compliance and risk summary",
    helpText: "Use the questions above to summarise the compliance position for the applicant.",
    kind: "textarea",
    required: false,
  },
];

export function getQuestionnaireProgress(answers: Record<string, string>) {
  const requiredQuestions = CLIENT_KYC_QUESTIONS.filter((question) => question.required);
  const answered = requiredQuestions.filter((question) => answers[question.id]?.trim()).length;

  return {
    answered,
    total: requiredQuestions.length,
    complete: answered === requiredQuestions.length,
  };
}
